site_name: Raphtory User Guide
site_url: http://raphtory.github.io

theme:
  palette:
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github
plugins:
  - mkdocs_matplotlib
  - search:
      lang: en
  - markdown-exec
  - macros:
      module_name: scripts/macro

extra:
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property:
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.snippets:
      base_path: ['.','docs/src/']
      check_paths: true
      dedent_subsections: true
  - footnotes
extra_css:
  - stylesheets/extra.css
repo_url: https://github.com/pometry/raphtory
repo_name: pometry/raphtory
watch:
  - scripts
  - docs/examples
  - docs/src
  - docs/stylesheets
  - docs/user-guide
nav:
  - Home: index.md
  - User Guide:
    - user-guide/installation.md
    - Getting data into Raphtory:
      -  user-guide/ingestion/1_creating-a-graph.md
      -  user-guide/ingestion/2_direct-updates.md
      -  user-guide/ingestion/3_dataframes.md
      -  user-guide/ingestion/4_saving.md
    - Querying:
      - user-guide/querying/1_intro.md
      - user-guide/querying/2_graph-metrics.md
      - user-guide/querying/3_vertex-metrics.md
      - user-guide/querying/4_edge-metrics.md
      - user-guide/querying/5_properties.md
      - user-guide/querying/6_chaining.md
    - Graph views:
      - user-guide/views/1_intro.md
      - user-guide/views/2_time.md
      - user-guide/views/3_layer.md
      - user-guide/views/4_subgraph.md
      - user-guide/views/5_materialize.md
    - Running Algorithms:
      - user-guide/algorithms/1_intro.md
      - user-guide/algorithms/2_graph-algorithms.md
      - user-guide/algorithms/3_vertex-algorithms.md
      - user-guide/algorithms/4_view-algorithms.md
    - Exporting:
      - user-guide/export/1_intro.md
      - user-guide/export/2_dataframes.md
      - user-guide/export/3_networkx.md
      - user-guide/export/4_pyvis.md
  - API: api.md 

hooks:
  - scripts/people.py

